name: react-resume-app
region: nyc

services:
  - name: backend
    source_dir: backend
    dockerfile_path: Dockerfile
    http_port: 8000
    envs:
      - key: SENDER_EMAIL
        scope: RUN_TIME
        value: ${SENDER_EMAIL}
      - key: APP_PASSWORD
        scope: RUN_TIME
        value: ${APP_PASSWORD}
      - key: CLOUDFLARE_SECRET_KEY
        scope: RUN_TIME
        value: ${CLOUDFLARE_SECRET_KEY}
      - key: SMTP_SERVER
        scope: RUN_TIME
        value: ${SMTP_SERVER}
      - key: SMTP_PORT
        scope: RUN_TIME
        value: ${SMTP_PORT}
      - key: MAIL_TO
        scope: RUN_TIME
        value: ${MAIL_TO}
      - key: ALLOWED_ORIGINS
        scope: RUN_TIME
        value: ${ALLOWED_ORIGINS}
    instance_count: 1
    instance_size_slug: basic-xxs

static_sites:
  - name: frontend
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${BACKEND_URL}
    routes:
      - path: /
    custom_domains:
      - domain: likouris.com
